task: detect 
mode: train 
# Train settings
model: /ultralytics-main/yolov8n.pt  
data: /cfg/datasets/data.yaml  
epochs: 300  
patience: 50 
batch: 32  
imgsz: 640 
save: True  
save_period: -1 
cache: False  
device: 
workers: 8 
project: runs
exist_ok: False  
pretrained: False  
optimizer: SGD  
verbose: True  
seed: 0 
deterministic: True  
single_cls: False  
rect: False  
cos_lr: False  
close_mosaic: 10  
resume: False 
amp: True 
fraction: 1.0  
profile: False  
freeze: None 

# Val/Test settings 
val: True  
split: val  
save_json: False 
save_hybrid: False  
conf: 0.001 
iou: 0.5 
max_det: 300  
half: False 
dnn: False 
plots: True  

# Predict settings 
source:/ultralytics-main/images  
vid_stride: 1 
stream_buffer: False 
visualize: False 
augment: False 
agnostic_nms: False 
retina_masks: False 
save: True 

# Visualize settings 
show: False 
save_frames: False 
save_txt: False  
save_conf: False  
save_crop: False 
show_labels: False 
show_conf: True 
show_boxes: True  

